name: Jehyun Park
author: Jehyun Park
baseurl: /
description: theme for jekyll
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
email: lovegjgjgj@naver.com

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
